name: Portfolio ci
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # - name: Checkstyle
    #   run: npm checkstyle:checkstyle

    # - name: SonarCloud Scan
    #   uses: sonarsource/sonarcloud-github-action@v2.2.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
    #   env:
    #     SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

    # Setup java 17 to be default (sonar-scanner requirement as of 5.x)
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    # Setup sonar-scanner
    - name: Setup SonarQube
      uses: warchant/setup-sonar-scanner@v7
    # Run sonar-scanner
    - name: SonarQube Scan
      run: sonar-scanner
           -Dsonar.host.url="https://sonarcloud.io"
           -Dsonar.login="17bc190f2deb1caece1c0b17d426115513abac5f"
           -Dsonar.organization="LearnDevops13"
           -Dsonar.projectKey="learndevops13_brunda"
           -Dsonar.sources=$GITHUB_WORKSPACE
